parse_config:
  raw_binding_map:
    # Symbole für AltGr (Right Alt) Kombinationen
    "&kp RA(N7)": "{"
    "&kp RA(N8)": "["
    "&kp RA(N9)": "]"
    "&kp RA(N0)": "}"
    "&kp RA(Q)": "@"
    "&kp RA(E)": "€"
    "&kp RA(MINUS)": "\\"
    "&kp RA(SQT)": "´"
    "&kp RA(RBKT)": "~"
    
    # Deutsche Umlaute (falls über ZMK-De-Header oder Alias genutzt)
    # Wenn du sie als Key-Codes sendest, hier die entsprechenden Mappings:
    "&kp DE_U_UMLAUT": "Ü"
    "&kp DE_A_UMLAUT": "Ä"
    "&kp DE_O_UMLAUT": "Ö"
    "&kp DE_SZ": "ß"

    # Sonderzeichen & Navigation
    "&kp NON_US_BSLH": "<"
    "&kp LS(NON_US_BSLH)": ">"
    "&kp RA(NON_US_BSLH)": "|"
    "&kp NON_US_HASH": "#"
    "&kp LS(GRAVE)": "°"
    "&kp GRAVE": "^"
    "&kp TILDE": "~"
    "&kp CARET": "^"

    # Behaviors/Macros hübsch machen
    "&durchmesser": "Ø"
    "&smiley": "☺"
    "&jigg_on": "Jig ON"
    "&jigg_off": "Jig OFF"

    # Layer & Media
    "&ext_power EP_TOG": "⚡ Toggle"
    "&out OUT_BLE": "BLE"
    "&out OUT_USB": "USB"

draw_config:
  dark_mode: true
  n_columns: 3
  split_gap: 30.0 # Macht die Lücke zwischen den Hälften etwas hübscher
