parse_config:
  raw_binding_map:
    # --- LAYER KEYS (Damit sie rot werden) ---
    "&lt 1 TAB": {t: "⇥", s: "Lower", type: "held"}
    "&lt 1 RET": {t: "↵", s: "Lower", type: "held"}
    "&lt 2 ESC": {t: "ESC", s: "Raise", type: "held"}
    "&lt_hp 2 SPACE": {t: "␣", s: "Raise", type: "held"}
    "&lt_hp 3 BSPC": {t: "⌫", s: "Adjust", type: "held"}
    "&mo 1": {t: "Lower", type: "held"}
    "&mo 2": {t: "Raise", type: "held"}
    "&mo 3": {t: "Adjust", type: "held"}

    # --- DEUTSCHE TASTEN & SYMBOLE ---
    "&kp LGUI": "$$mdi:microsoft-windows-classic$$"
    "&kp LC(LS(ESC))": "Task Mgr"
    "&nbsp": "NBSP"
    "&kp HOME": "⤒ Pos1"
    "&kp END": "⤓ End"

draw_config:
  dark_mode: true
  n_columns: 1
  # Falls das Layout immer noch verschoben ist, lösche key_w und key_h!
  # Er nutzt dann die Standardwerte deiner Aurora Corne.
  
