manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import:
        # Pfad zur Datei innerhalb des ZMK Repos
        path: app/west.yml
        # Exclude muss direkt unter import stehen
        exclude:
          - hal_altera
          - hal_ambiq
          - hal_espressif
          - hal_gigadevice
          - hal_infineon
          - hal_intel
          - hal_microchip
          - hal_nxp
          - hal_openisa
          - hal_quicklogic
          - hal_renesas
          - hal_silabs
          - hal_st
          - hal_ti
          - hal_telink
    - name: nice-view-gem
      url: https://github.com/MageSlayer/nice-view-gem
      revision: main
  self:
    path: config
