manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: mageslayer # Neu hinzufügen
      url-base: https://github.com/MageSlayer
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: nice-view-gem # Neu hinzufügen
      remote: mageslayer
      revision: main
