# In der west.yml
projects:
  - name: zmk
    remote: zmkfirmware
    revision: main
    import: app/west.yml
  - name: nice-view-gem
    url: https://github.com/MageSlayer/nice-view-gem
    revision: main
