name: Draw ZMK keymaps
on:
  workflow_dispatch: # Erlaubt manuelles Starten
  push:
    paths:
      - "config/*.keymap"
      - "config/*.dtsi"
      - ".github/workflows/draw-keymap.yml"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    with:
      keymap_patterns: "config/*.keymap"
      output_folder: "keymap-drawer"
      # install_args wurde entfernt, da nicht mehr ben√∂tigt
      commit_message: "docs: [keymap-drawer] automatische Aktualisierung der Keymap-Grafik"
